# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Group/~create/$",
        view=views.GroupCreateView.as_view(),
        name='Group_create',
    ),
    url(
        regex="^Group/(?P<pk>\d+)/~delete/$",
        view=views.GroupDeleteView.as_view(),
        name='Group_delete',
    ),
    url(
        regex="^Group/(?P<pk>\d+)/$",
        view=views.GroupDetailView.as_view(),
        name='Group_detail',
    ),
    url(
        regex="^Group/(?P<pk>\d+)/~update/$",
        view=views.GroupUpdateView.as_view(),
        name='Group_update',
    ),
    url(
        regex="^Group/$",
        view=views.GroupListView.as_view(),
        name='Group_list',
    ),
	url(
        regex="^Taxonomy/~create/$",
        view=views.TaxonomyCreateView.as_view(),
        name='Taxonomy_create',
    ),
    url(
        regex="^Taxonomy/(?P<pk>\d+)/~delete/$",
        view=views.TaxonomyDeleteView.as_view(),
        name='Taxonomy_delete',
    ),
    url(
        regex="^Taxonomy/(?P<pk>\d+)/$",
        view=views.TaxonomyDetailView.as_view(),
        name='Taxonomy_detail',
    ),
    url(
        regex="^Taxonomy/(?P<pk>\d+)/~update/$",
        view=views.TaxonomyUpdateView.as_view(),
        name='Taxonomy_update',
    ),
    url(
        regex="^Taxonomy/$",
        view=views.TaxonomyListView.as_view(),
        name='Taxonomy_list',
    ),
	url(
        regex="^Collection/~create/$",
        view=views.CollectionCreateView.as_view(),
        name='Collection_create',
    ),
    url(
        regex="^Collection/(?P<pk>\d+)/~delete/$",
        view=views.CollectionDeleteView.as_view(),
        name='Collection_delete',
    ),
    url(
        regex="^Collection/(?P<pk>\d+)/$",
        view=views.CollectionDetailView.as_view(),
        name='Collection_detail',
    ),
    url(
        regex="^Collection/(?P<pk>\d+)/~update/$",
        view=views.CollectionUpdateView.as_view(),
        name='Collection_update',
    ),
    url(
        regex="^Collection/$",
        view=views.CollectionListView.as_view(),
        name='Collection_list',
    ),
	url(
        regex="^Content/~create/$",
        view=views.ContentCreateView.as_view(),
        name='Content_create',
    ),
    url(
        regex="^Content/(?P<pk>\d+)/~delete/$",
        view=views.ContentDeleteView.as_view(),
        name='Content_delete',
    ),
    url(
        regex="^Content/(?P<pk>\d+)/$",
        view=views.ContentDetailView.as_view(),
        name='Content_detail',
    ),
    url(
        regex="^Content/(?P<pk>\d+)/~update/$",
        view=views.ContentUpdateView.as_view(),
        name='Content_update',
    ),
    url(
        regex="^Content/$",
        view=views.ContentListView.as_view(),
        name='Content_list',
    ),
	url(
        regex="^Attachment/~create/$",
        view=views.AttachmentCreateView.as_view(),
        name='Attachment_create',
    ),
    url(
        regex="^Attachment/(?P<pk>\d+)/~delete/$",
        view=views.AttachmentDeleteView.as_view(),
        name='Attachment_delete',
    ),
    url(
        regex="^Attachment/(?P<pk>\d+)/$",
        view=views.AttachmentDetailView.as_view(),
        name='Attachment_detail',
    ),
    url(
        regex="^Attachment/(?P<pk>\d+)/~update/$",
        view=views.AttachmentUpdateView.as_view(),
        name='Attachment_update',
    ),
    url(
        regex="^Attachment/$",
        view=views.AttachmentListView.as_view(),
        name='Attachment_list',
    ),
	url(
        regex="^Sitemap/~create/$",
        view=views.SitemapCreateView.as_view(),
        name='Sitemap_create',
    ),
    url(
        regex="^Sitemap/(?P<pk>\d+)/~delete/$",
        view=views.SitemapDeleteView.as_view(),
        name='Sitemap_delete',
    ),
    url(
        regex="^Sitemap/(?P<pk>\d+)/$",
        view=views.SitemapDetailView.as_view(),
        name='Sitemap_detail',
    ),
    url(
        regex="^Sitemap/(?P<pk>\d+)/~update/$",
        view=views.SitemapUpdateView.as_view(),
        name='Sitemap_update',
    ),
    url(
        regex="^Sitemap/$",
        view=views.SitemapListView.as_view(),
        name='Sitemap_list',
    ),
	url(
        regex="^Page/~create/$",
        view=views.PageCreateView.as_view(),
        name='Page_create',
    ),
    url(
        regex="^Page/(?P<pk>\d+)/~delete/$",
        view=views.PageDeleteView.as_view(),
        name='Page_delete',
    ),
    url(
        regex="^Page/(?P<pk>\d+)/$",
        view=views.PageDetailView.as_view(),
        name='Page_detail',
    ),
    url(
        regex="^Page/(?P<pk>\d+)/~update/$",
        view=views.PageUpdateView.as_view(),
        name='Page_update',
    ),
    url(
        regex="^Page/$",
        view=views.PageListView.as_view(),
        name='Page_list',
    ),
	
]
